/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package id.project;

import java.awt.Toolkit;
import java.text.SimpleDateFormat;

/**
 *
 * @author Mostafa
 */
public class calculateDates extends javax.swing.JFrame {

    /**
     * Creates new form calculateDates
     */
    public calculateDates() {
        initComponents();
        iconImage();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        h1 = new com.toedter.calendar.JDateChooser();
        h2 = new com.toedter.calendar.JDateChooser();
        tf1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 153));
        setForeground(new java.awt.Color(0, 0, 153));
        setMinimumSize(new java.awt.Dimension(400, 310));
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("From :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 40, 120, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("To    :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 100, 110, 40);
        getContentPane().add(h1);
        h1.setBounds(190, 40, 110, 40);
        getContentPane().add(h2);
        h2.setBounds(190, 100, 110, 40);

        tf1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tf1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf1ActionPerformed(evt);
            }
        });
        getContentPane().add(tf1);
        tf1.setBounds(0, 230, 380, 40);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(140, 160, 100, 31);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id/project/icon2.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(190, 0, 190, 300);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id/project/icon2.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 190, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      SimpleDateFormat d1 = new SimpleDateFormat("dd");
        SimpleDateFormat m1 = new SimpleDateFormat("MM");
        SimpleDateFormat y1 = new SimpleDateFormat("YYYY");

        int i = (int) Double.parseDouble(d1.format(h1.getDate()));
        int i1 = (int) Double.parseDouble(m1.format(h1.getDate()));
        int i2 = (int) Double.parseDouble(y1.format(h1.getDate()));

        int l = (int) Double.parseDouble(d1.format(h2.getDate()));
        int l1 = (int) Double.parseDouble(m1.format(h2.getDate()));
        int l2 = (int) Double.parseDouble(y1.format(h2.getDate()));
        int fy ;
        int fd ;
        int fm ;

        fy = l2 - i2 ;
        fm = l1 - i1 ;
        fd = l - i ;

        if (fd<=0){
            fd+=30 ;
            fm-=1;
            if (fm<0){
                fm+=12 ;
                fy-=1 ;
                if (fy<0){
                    tf1.setText("Please enter correct data ");
                }
                else{
                    tf1.setText( String.valueOf(fy) +" year/s ," + String.valueOf(fm) + " month/s and " + String.valueOf(fd) + " day/s " );

                }
            }
            else{
                tf1.setText( String.valueOf(fy) +" year/s ," + String.valueOf(fm) + " month/s and " + String.valueOf(fd) + " day/s " );
            }

        }
        else{
            if (fm<0){
                fm+=12;
                fy-=1;
                if (fy < 0 ){
                    tf1.setText("Please enter correct data");
                }
                else{
                    tf1.setText( String.valueOf(fy) +" year/s ," + String.valueOf(fm) + " month/s and " + String.valueOf(fd) + " day/s " );
                }
            }
            else  {
                if (fy < 0 ){
                    tf1.setText("Please enter correct data");
                }
                else {
                    tf1.setText( String.valueOf(fy) +" year/s ," + String.valueOf(fm) + " month/s and " + String.valueOf(fd) + " day/s " );
                }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculateDates.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculateDates.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculateDates.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculateDates.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculateDates().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser h1;
    private com.toedter.calendar.JDateChooser h2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField tf1;
    // End of variables declaration//GEN-END:variables

    private void iconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.jpg")));
    }
}
