/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package id.project;

import java.awt.Toolkit;

/**
 *
 * @author Mostafa
 */
public class stopWatch extends javax.swing.JFrame {
static int milli = 0 ;
    static int second = 0;
static int minute = 0 ;
static int hour = 0 ;
boolean k = true ; 
    /**
     * Creates new form stopWatch
     */
    public stopWatch() {
        initComponents();
        iconImage();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        start = new javax.swing.JButton();
        stop = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        tfh = new javax.swing.JLabel();
        tfm = new javax.swing.JLabel();
        tfs = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(502, 200));
        getContentPane().setLayout(null);

        start.setBackground(new java.awt.Color(255, 255, 255));
        start.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        start.setForeground(new java.awt.Color(0, 0, 153));
        start.setText("start");
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });
        getContentPane().add(start);
        start.setBounds(175, 116, 149, 37);

        stop.setBackground(new java.awt.Color(255, 255, 255));
        stop.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        stop.setForeground(new java.awt.Color(0, 0, 153));
        stop.setText("stop");
        stop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopActionPerformed(evt);
            }
        });
        getContentPane().add(stop);
        stop.setBounds(10, 116, 155, 37);

        reset.setBackground(new java.awt.Color(255, 255, 255));
        reset.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        reset.setForeground(new java.awt.Color(0, 0, 153));
        reset.setText("reset");
        reset.setMaximumSize(new java.awt.Dimension(55, 23));
        reset.setMinimumSize(new java.awt.Dimension(55, 33));
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        getContentPane().add(reset);
        reset.setBounds(330, 116, 160, 37);

        tfh.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        tfh.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(tfh);
        tfh.setBounds(10, 11, 155, 87);

        tfm.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        tfm.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(tfm);
        tfm.setBounds(175, 11, 149, 87);

        tfs.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        tfs.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(tfs);
        tfs.setBounds(330, 11, 160, 87);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id/project/icon4.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(4, 0, 490, 160);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
        Thread i = new Thread(){
            public void run(){
                k=true ;
                for(int j = 1 ; j>0; j++){

                    try{
                        sleep(1000);
                        if(k==true&&second < 60) {
                            second++ ;

                        }
                        else if (k==true&&minute < 60)
                        {
                            second = 0 ;
                            minute++ ;
                        }
                        else if (k==true&&hour<9000){
                            second = 0 ;
                            minute = 0 ;
                            hour++ ;
                        }
                        System.out.println(second);
                        tfs.setText(String.valueOf(second));
                        tfm.setText(String.valueOf(minute +" :"));
                        tfh.setText(String.valueOf(hour+" :"));
                    }
                    catch(Exception e){
                        System.out.println("error");
                    }
                }

            }
        };
        i.start();
    }//GEN-LAST:event_startActionPerformed

    private void stopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopActionPerformed
        k = false ;
    }//GEN-LAST:event_stopActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        second = 0 ;
        minute = 0 ;
        hour = 0 ;

        k= false ;
    }//GEN-LAST:event_resetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(stopWatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(stopWatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(stopWatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(stopWatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new stopWatch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton reset;
    private javax.swing.JButton start;
    private javax.swing.JButton stop;
    private javax.swing.JLabel tfh;
    private javax.swing.JLabel tfm;
    private javax.swing.JLabel tfs;
    // End of variables declaration//GEN-END:variables

    private void iconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.jpg")));
    }
}
